name: Action
on:
  push:
    branches:
      - main

jobs:
  unit_test:
    name: unit_test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --silent --frozen-lockfile
      - run: npm run test
      - run: npm run test:e2e

  deploy_vps:
    name: deploy_vps
    runs-on: ubuntu-latest
    needs: [unit_test]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd .ci && yarn install --silent
      - run: node ./.ci/script/deploy.js
        env:
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_KEY: ${{secrets.SSH_KEY}}

  build_vps:
    name: build_vps
    runs-on: ubuntu-latest
    needs: [deploy_vps]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd .ci && yarn install --silent
      - run: node ./.ci/script/build.js
        env:
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_KEY: ${{secrets.SSH_KEY}}

  restart_vps:
    name: restart_vps
    runs-on: ubuntu-latest
    needs: [build_vps]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd .ci && yarn install --silent
      - run: node ./.ci/script/restart.js
        env:
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_KEY: ${{secrets.SSH_KEY}}